### ISSUE TITLE
10 - Create group

### ISSUE THREAD

**Issue by taunojokinen** [TVT23KM-1/Muuvit#11]
G7 - Kirjautunut käyttäjä voi luoda uuden ryhmän valitsemallaan nimellä.
Ryhmällä on oma näkymä, jonka saa näkyviin vain ryhmän jäsen.
Lista luoduista ryhmistä (ryhmien nimet ja kuvaukset) tulee näkyä
kirjautumatta sovelluksessa. Omistaja voi myös poistaa ryhmän.

**Comment by mkuja** [comment]
Backend-osuus ryhmien luomisesta toimii, ja frontissa on valmis formi jonka voi laittaa jollekin sivulle ryhmän luomista varten. 

Kokonaisuutena ryhmän luominen on tämän formin sijoittamista vaille valmis.
