### ISSUE TITLE
18 - Post reviews

### ISSUE THREAD

**Issue by taunojokinen** [TVT23KM-1/Muuvit#18]
G11 - Kirjautunut käyttäjä voi lisätä uuden leffa-arvostelun järjestelmään.
Leffasta annetaan tähdet ja lyhyt arvosteluteksti. Arvostelussa tulee
näkyä käyttäjän nimimerkki ja mahdollisuus avata tarkemmat tiedot
elokuvasta.

**Comment by mkuja** [comment]
Tällä hetkellä reviewn kirjoitus widgetti ei ole responsiivinen.
